import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import NavigationMenu from '@/navigation/molecules/NavigationMenu'
import createEmotionCache from "../utils/createEmotionCache";
import { CacheProvider } from "@emotion/react";
import Header from '@/header/organisms/Header'


//const clientSideEmotionCache = createEmotionCache();

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
    <Header/>
    <NavigationMenu/>
    
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={styles.main}>
        
      <ul>
      <li>
        <Link href="/">Home</Link>
      </li>
      <li>
        <Link href="/register">Register</Link>
      </li>
      <li>
        <Link href="/login">Login</Link>
      </li>
    </ul>
      </main>
    </>
  )
}
